//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2C2P.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public string TransactionId { get; set; }
        public double Amount { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTimeOffset> TransactionDate { get; set; }
        public string Status { get; set; }
    }
}
